var annotated_dup =
[
    [ "Span", "namespaceSpan.html", [
      [ "Internal", "namespaceSpan_1_1Internal.html", [
        [ "ImGuiVisitor", "structSpan_1_1Internal_1_1ImGuiVisitor.html", "structSpan_1_1Internal_1_1ImGuiVisitor" ],
        [ "JsonSerializeVisitor", "structSpan_1_1Internal_1_1JsonSerializeVisitor.html", "structSpan_1_1Internal_1_1JsonSerializeVisitor" ],
        [ "JsonDeserializeVisitor", "structSpan_1_1Internal_1_1JsonDeserializeVisitor.html", "structSpan_1_1Internal_1_1JsonDeserializeVisitor" ]
      ] ],
      [ "FixedString", "structSpan_1_1FixedString.html", "structSpan_1_1FixedString" ],
      [ "Input", "classSpan_1_1Input.html", "classSpan_1_1Input" ],
      [ "Logger", "classSpan_1_1Logger.html", "classSpan_1_1Logger" ],
      [ "Vector2", "structSpan_1_1Vector2.html", "structSpan_1_1Vector2" ],
      [ "Vector3", "structSpan_1_1Vector3.html", "structSpan_1_1Vector3" ],
      [ "Vector4", "structSpan_1_1Vector4.html", "structSpan_1_1Vector4" ],
      [ "Quaternion", "structSpan_1_1Quaternion.html", "structSpan_1_1Quaternion" ],
      [ "Matrix4x4", "structSpan_1_1Matrix4x4.html", "structSpan_1_1Matrix4x4" ],
      [ "MemoryArena", "classSpan_1_1MemoryArena.html", "classSpan_1_1MemoryArena" ],
      [ "Time", "classSpan_1_1Time.html", "classSpan_1_1Time" ],
      [ "RenameFileCommand", "classSpan_1_1RenameFileCommand.html", "classSpan_1_1RenameFileCommand" ],
      [ "MoveFileCommand", "classSpan_1_1MoveFileCommand.html", "classSpan_1_1MoveFileCommand" ],
      [ "DeleteFileCommand", "classSpan_1_1DeleteFileCommand.html", "classSpan_1_1DeleteFileCommand" ],
      [ "CreateFileCommand", "classSpan_1_1CreateFileCommand.html", "classSpan_1_1CreateFileCommand" ],
      [ "CreateDirectoryCommand", "classSpan_1_1CreateDirectoryCommand.html", "classSpan_1_1CreateDirectoryCommand" ],
      [ "ICommand", "classSpan_1_1ICommand.html", "classSpan_1_1ICommand" ],
      [ "GuiManager", "classSpan_1_1GuiManager.html", "classSpan_1_1GuiManager" ],
      [ "ImGuiUI", "classSpan_1_1ImGuiUI.html", "classSpan_1_1ImGuiUI" ],
      [ "EditorPanel", "classSpan_1_1EditorPanel.html", "classSpan_1_1EditorPanel" ],
      [ "EnvironmentPanel", "classSpan_1_1EnvironmentPanel.html", "classSpan_1_1EnvironmentPanel" ],
      [ "HierarchyPanel", "classSpan_1_1HierarchyPanel.html", "classSpan_1_1HierarchyPanel" ],
      [ "InspectorPanel", "classSpan_1_1InspectorPanel.html", "classSpan_1_1InspectorPanel" ],
      [ "MaterialPreviewer", "classSpan_1_1MaterialPreviewer.html", "classSpan_1_1MaterialPreviewer" ],
      [ "ProjectBrowserPanel", "classSpan_1_1ProjectBrowserPanel.html", "classSpan_1_1ProjectBrowserPanel" ],
      [ "SceneViewPanel", "classSpan_1_1SceneViewPanel.html", "classSpan_1_1SceneViewPanel" ],
      [ "SelectionManager", "classSpan_1_1SelectionManager.html", "classSpan_1_1SelectionManager" ],
      [ "DirectoryWatcher", "classSpan_1_1DirectoryWatcher.html", "classSpan_1_1DirectoryWatcher" ],
      [ "EditorFileSystem", "classSpan_1_1EditorFileSystem.html", "classSpan_1_1EditorFileSystem" ],
      [ "FileDialog", "classSpan_1_1FileDialog.html", "classSpan_1_1FileDialog" ],
      [ "Application", "classSpan_1_1Application.html", "classSpan_1_1Application" ],
      [ "Active", "structSpan_1_1Active.html", "structSpan_1_1Active" ],
      [ "IDComponent", "structSpan_1_1IDComponent.html", "structSpan_1_1IDComponent" ],
      [ "Layer", "structSpan_1_1Layer.html", "structSpan_1_1Layer" ],
      [ "LocalToWorld", "structSpan_1_1LocalToWorld.html", "structSpan_1_1LocalToWorld" ],
      [ "Name", "structSpan_1_1Name.html", "structSpan_1_1Name" ],
      [ "Relationship", "structSpan_1_1Relationship.html", "structSpan_1_1Relationship" ],
      [ "Tag", "structSpan_1_1Tag.html", "structSpan_1_1Tag" ],
      [ "Transform", "structSpan_1_1Transform.html", "structSpan_1_1Transform" ],
      [ "EditorCamera", "structSpan_1_1EditorCamera.html", "structSpan_1_1EditorCamera" ],
      [ "Camera", "structSpan_1_1Camera.html", "structSpan_1_1Camera" ],
      [ "DirectionalLight", "structSpan_1_1DirectionalLight.html", "structSpan_1_1DirectionalLight" ],
      [ "MeshFilter", "structSpan_1_1MeshFilter.html", "structSpan_1_1MeshFilter" ],
      [ "MeshRenderer", "structSpan_1_1MeshRenderer.html", "structSpan_1_1MeshRenderer" ],
      [ "PointLight", "structSpan_1_1PointLight.html", "structSpan_1_1PointLight" ],
      [ "SpotLight", "structSpan_1_1SpotLight.html", "structSpan_1_1SpotLight" ],
      [ "LayerManager", "classSpan_1_1LayerManager.html", "classSpan_1_1LayerManager" ],
      [ "TagManager", "classSpan_1_1TagManager.html", "classSpan_1_1TagManager" ],
      [ "ComponentTypeCounter", "classSpan_1_1ComponentTypeCounter.html", "classSpan_1_1ComponentTypeCounter" ],
      [ "ComponentType", "classSpan_1_1ComponentType.html", "classSpan_1_1ComponentType" ],
      [ "ArchetypeSignature", "classSpan_1_1ArchetypeSignature.html", "classSpan_1_1ArchetypeSignature" ],
      [ "Archetype", "classSpan_1_1Archetype.html", "classSpan_1_1Archetype" ],
      [ "ArchetypeManager", "classSpan_1_1ArchetypeManager.html", "classSpan_1_1ArchetypeManager" ],
      [ "Chunk", "structSpan_1_1Chunk.html", "structSpan_1_1Chunk" ],
      [ "EntityID", "structSpan_1_1EntityID.html", "structSpan_1_1EntityID" ],
      [ "Entity", "structSpan_1_1Entity.html", "structSpan_1_1Entity" ],
      [ "EntityBuilder", "classSpan_1_1EntityBuilder.html", "classSpan_1_1EntityBuilder" ],
      [ "EntityManager", "classSpan_1_1EntityManager.html", "classSpan_1_1EntityManager" ],
      [ "System", "classSpan_1_1System.html", "classSpan_1_1System" ],
      [ "EntityLocation", "structSpan_1_1EntityLocation.html", "structSpan_1_1EntityLocation" ],
      [ "World", "classSpan_1_1World.html", "classSpan_1_1World" ],
      [ "ComputeBuffer", "classSpan_1_1ComputeBuffer.html", "classSpan_1_1ComputeBuffer" ],
      [ "ConstantBuffer", "classSpan_1_1ConstantBuffer.html", "classSpan_1_1ConstantBuffer" ],
      [ "GraphicsContext", "classSpan_1_1GraphicsContext.html", "classSpan_1_1GraphicsContext" ],
      [ "IBLBuilder", "classSpan_1_1IBLBuilder.html", "classSpan_1_1IBLBuilder" ],
      [ "LightManager", "classSpan_1_1LightManager.html", "classSpan_1_1LightManager" ],
      [ "RenderPassManager", "classSpan_1_1RenderPassManager.html", "classSpan_1_1RenderPassManager" ],
      [ "RenderTarget", "classSpan_1_1RenderTarget.html", "classSpan_1_1RenderTarget" ],
      [ "Shader", "classSpan_1_1Shader.html", "classSpan_1_1Shader" ],
      [ "ShadowMap", "classSpan_1_1ShadowMap.html", "classSpan_1_1ShadowMap" ],
      [ "ModelLoader", "classSpan_1_1ModelLoader.html", "classSpan_1_1ModelLoader" ],
      [ "DepthNormalPass", "classSpan_1_1DepthNormalPass.html", "classSpan_1_1DepthNormalPass" ],
      [ "GridPass", "classSpan_1_1GridPass.html", "classSpan_1_1GridPass" ],
      [ "ShadowPass", "classSpan_1_1ShadowPass.html", "classSpan_1_1ShadowPass" ],
      [ "SkyboxPass", "classSpan_1_1SkyboxPass.html", "classSpan_1_1SkyboxPass" ],
      [ "SSAOBlurPass", "classSpan_1_1SSAOBlurPass.html", "classSpan_1_1SSAOBlurPass" ],
      [ "SSAOPass", "classSpan_1_1SSAOPass.html", "classSpan_1_1SSAOPass" ],
      [ "TransformData", "structSpan_1_1TransformData.html", "structSpan_1_1TransformData" ],
      [ "LightDataGPU", "structSpan_1_1LightDataGPU.html", "structSpan_1_1LightDataGPU" ],
      [ "GlobalLightData", "structSpan_1_1GlobalLightData.html", "structSpan_1_1GlobalLightData" ],
      [ "Renderer", "classSpan_1_1Renderer.html", "classSpan_1_1Renderer" ],
      [ "MaterialData", "structSpan_1_1MaterialData.html", "structSpan_1_1MaterialData" ],
      [ "Material", "classSpan_1_1Material.html", "classSpan_1_1Material" ],
      [ "Vertex", "structSpan_1_1Vertex.html", "structSpan_1_1Vertex" ],
      [ "Mesh", "classSpan_1_1Mesh.html", "classSpan_1_1Mesh" ],
      [ "Texture", "classSpan_1_1Texture.html", "classSpan_1_1Texture" ],
      [ "WindowDesc", "structSpan_1_1WindowDesc.html", "structSpan_1_1WindowDesc" ],
      [ "Window", "classSpan_1_1Window.html", "classSpan_1_1Window" ],
      [ "ComponentMetadata", "structSpan_1_1ComponentMetadata.html", "structSpan_1_1ComponentMetadata" ],
      [ "ComponentRegistry", "classSpan_1_1ComponentRegistry.html", "classSpan_1_1ComponentRegistry" ],
      [ "Attribute", "structSpan_1_1Attribute.html", "structSpan_1_1Attribute" ],
      [ "is_fixed_string", "structSpan_1_1is__fixed__string.html", null ],
      [ "is_fixed_string&lt; FixedString&lt; N &gt; &gt;", "structSpan_1_1is__fixed__string_3_01FixedString_3_01N_01_4_01_4.html", null ],
      [ "AssetManager", "classSpan_1_1AssetManager.html", "classSpan_1_1AssetManager" ],
      [ "AssetMetadata", "structSpan_1_1AssetMetadata.html", "structSpan_1_1AssetMetadata" ],
      [ "AssetRegistry", "classSpan_1_1AssetRegistry.html", "classSpan_1_1AssetRegistry" ],
      [ "AssetSerializer", "classSpan_1_1AssetSerializer.html", "classSpan_1_1AssetSerializer" ],
      [ "EnvironmentSettings", "structSpan_1_1EnvironmentSettings.html", "structSpan_1_1EnvironmentSettings" ],
      [ "EditorCameraState", "structSpan_1_1EditorCameraState.html", "structSpan_1_1EditorCameraState" ],
      [ "Scene", "classSpan_1_1Scene.html", "classSpan_1_1Scene" ],
      [ "SceneSerializer", "classSpan_1_1SceneSerializer.html", "classSpan_1_1SceneSerializer" ],
      [ "RelationshipSystem", "classSpan_1_1RelationshipSystem.html", "classSpan_1_1RelationshipSystem" ],
      [ "TransformSystem", "classSpan_1_1TransformSystem.html", "classSpan_1_1TransformSystem" ],
      [ "CameraSystem", "classSpan_1_1CameraSystem.html", "classSpan_1_1CameraSystem" ],
      [ "EditorCameraSystem", "classSpan_1_1EditorCameraSystem.html", "classSpan_1_1EditorCameraSystem" ],
      [ "RenderingSystem", "classSpan_1_1RenderingSystem.html", "classSpan_1_1RenderingSystem" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash&lt; Span::EntityID &gt;", "structstd_1_1hash_3_01Span_1_1EntityID_01_4.html", "structstd_1_1hash_3_01Span_1_1EntityID_01_4" ]
    ] ]
];