var annotated_dup =
[
    [ "Span", "namespaceSpan.html", [
      [ "Input", "classSpan_1_1Input.html", "classSpan_1_1Input" ],
      [ "Logger", "classSpan_1_1Logger.html", "classSpan_1_1Logger" ],
      [ "Vector2", "structSpan_1_1Vector2.html", "structSpan_1_1Vector2" ],
      [ "Vector3", "structSpan_1_1Vector3.html", "structSpan_1_1Vector3" ],
      [ "Vector4", "structSpan_1_1Vector4.html", "structSpan_1_1Vector4" ],
      [ "Quaternion", "structSpan_1_1Quaternion.html", "structSpan_1_1Quaternion" ],
      [ "Matrix4x4", "structSpan_1_1Matrix4x4.html", "structSpan_1_1Matrix4x4" ],
      [ "MemoryArena", "classSpan_1_1MemoryArena.html", "classSpan_1_1MemoryArena" ],
      [ "Time", "classSpan_1_1Time.html", "classSpan_1_1Time" ],
      [ "GuiManager", "classSpan_1_1GuiManager.html", "classSpan_1_1GuiManager" ],
      [ "ImGuiUI", "classSpan_1_1ImGuiUI.html", "classSpan_1_1ImGuiUI" ],
      [ "EditorPanel", "classSpan_1_1EditorPanel.html", "classSpan_1_1EditorPanel" ],
      [ "HierarchyPanel", "classSpan_1_1HierarchyPanel.html", "classSpan_1_1HierarchyPanel" ],
      [ "InspectorPanel", "classSpan_1_1InspectorPanel.html", "classSpan_1_1InspectorPanel" ],
      [ "SceneViewPanel", "classSpan_1_1SceneViewPanel.html", "classSpan_1_1SceneViewPanel" ],
      [ "SelectionManager", "classSpan_1_1SelectionManager.html", "classSpan_1_1SelectionManager" ],
      [ "Application", "classSpan_1_1Application.html", "classSpan_1_1Application" ],
      [ "Active", "structSpan_1_1Active.html", "structSpan_1_1Active" ],
      [ "Layer", "structSpan_1_1Layer.html", "structSpan_1_1Layer" ],
      [ "LocalToWorld", "structSpan_1_1LocalToWorld.html", "structSpan_1_1LocalToWorld" ],
      [ "Name", "structSpan_1_1Name.html", "structSpan_1_1Name" ],
      [ "Relationship", "structSpan_1_1Relationship.html", "structSpan_1_1Relationship" ],
      [ "Tag", "structSpan_1_1Tag.html", "structSpan_1_1Tag" ],
      [ "Transform", "structSpan_1_1Transform.html", "structSpan_1_1Transform" ],
      [ "EditorCamera", "structSpan_1_1EditorCamera.html", null ],
      [ "Camera", "structSpan_1_1Camera.html", "structSpan_1_1Camera" ],
      [ "MeshFilter", "structSpan_1_1MeshFilter.html", "structSpan_1_1MeshFilter" ],
      [ "MeshRenderer", "structSpan_1_1MeshRenderer.html", "structSpan_1_1MeshRenderer" ],
      [ "ComponentType", "classSpan_1_1ComponentType.html", "classSpan_1_1ComponentType" ],
      [ "ArchetypeSignature", "classSpan_1_1ArchetypeSignature.html", "classSpan_1_1ArchetypeSignature" ],
      [ "Archetype", "classSpan_1_1Archetype.html", "classSpan_1_1Archetype" ],
      [ "ArchetypeManager", "classSpan_1_1ArchetypeManager.html", "classSpan_1_1ArchetypeManager" ],
      [ "Chunk", "structSpan_1_1Chunk.html", "structSpan_1_1Chunk" ],
      [ "EntityID", "structSpan_1_1EntityID.html", "structSpan_1_1EntityID" ],
      [ "Entity", "structSpan_1_1Entity.html", "structSpan_1_1Entity" ],
      [ "EntityBuilder", "classSpan_1_1EntityBuilder.html", "classSpan_1_1EntityBuilder" ],
      [ "EntityManager", "classSpan_1_1EntityManager.html", "classSpan_1_1EntityManager" ],
      [ "System", "classSpan_1_1System.html", "classSpan_1_1System" ],
      [ "EntityLocation", "structSpan_1_1EntityLocation.html", "structSpan_1_1EntityLocation" ],
      [ "World", "classSpan_1_1World.html", "classSpan_1_1World" ],
      [ "ConstantBuffer", "classSpan_1_1ConstantBuffer.html", "classSpan_1_1ConstantBuffer" ],
      [ "GraphicsContext", "classSpan_1_1GraphicsContext.html", "classSpan_1_1GraphicsContext" ],
      [ "RenderTarget", "classSpan_1_1RenderTarget.html", "classSpan_1_1RenderTarget" ],
      [ "Shader", "classSpan_1_1Shader.html", "classSpan_1_1Shader" ],
      [ "ModelLoader", "classSpan_1_1ModelLoader.html", "classSpan_1_1ModelLoader" ],
      [ "TransformData", "structSpan_1_1TransformData.html", "structSpan_1_1TransformData" ],
      [ "Renderer", "classSpan_1_1Renderer.html", "classSpan_1_1Renderer" ],
      [ "MaterialData", "structSpan_1_1MaterialData.html", "structSpan_1_1MaterialData" ],
      [ "Material", "classSpan_1_1Material.html", "classSpan_1_1Material" ],
      [ "Vertex", "structSpan_1_1Vertex.html", "structSpan_1_1Vertex" ],
      [ "Mesh", "classSpan_1_1Mesh.html", "classSpan_1_1Mesh" ],
      [ "Texture", "classSpan_1_1Texture.html", "classSpan_1_1Texture" ],
      [ "WindowDesc", "structSpan_1_1WindowDesc.html", "structSpan_1_1WindowDesc" ],
      [ "Window", "classSpan_1_1Window.html", "classSpan_1_1Window" ],
      [ "ComponentMetadata", "structSpan_1_1ComponentMetadata.html", "structSpan_1_1ComponentMetadata" ],
      [ "ComponentRegistry", "classSpan_1_1ComponentRegistry.html", "classSpan_1_1ComponentRegistry" ],
      [ "Attribute", "structSpan_1_1Attribute.html", "structSpan_1_1Attribute" ],
      [ "RelationshipSystem", "classSpan_1_1RelationshipSystem.html", "classSpan_1_1RelationshipSystem" ],
      [ "TransformSystem", "classSpan_1_1TransformSystem.html", "classSpan_1_1TransformSystem" ],
      [ "CameraSystem", "classSpan_1_1CameraSystem.html", "classSpan_1_1CameraSystem" ],
      [ "EditorCameraSystem", "classSpan_1_1EditorCameraSystem.html", "classSpan_1_1EditorCameraSystem" ],
      [ "RenderingSystem", "classSpan_1_1RenderingSystem.html", "classSpan_1_1RenderingSystem" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash&lt; Span::EntityID &gt;", "structstd_1_1hash_3_01Span_1_1EntityID_01_4.html", "structstd_1_1hash_3_01Span_1_1EntityID_01_4" ]
    ] ]
];