var hierarchy =
[
    [ "Span::Active", "structSpan_1_1Active.html", null ],
    [ "Span::Application", "classSpan_1_1Application.html", null ],
    [ "Span::Archetype", "classSpan_1_1Archetype.html", null ],
    [ "Span::ArchetypeManager", "classSpan_1_1ArchetypeManager.html", null ],
    [ "Span::ArchetypeSignature", "classSpan_1_1ArchetypeSignature.html", null ],
    [ "Span::AssetManager", "classSpan_1_1AssetManager.html", null ],
    [ "Span::AssetMetadata", "structSpan_1_1AssetMetadata.html", null ],
    [ "Span::AssetRegistry", "classSpan_1_1AssetRegistry.html", null ],
    [ "Span::AssetSerializer", "classSpan_1_1AssetSerializer.html", null ],
    [ "Span::Attribute", "structSpan_1_1Attribute.html", null ],
    [ "Span::Camera", "structSpan_1_1Camera.html", null ],
    [ "Span::Chunk", "structSpan_1_1Chunk.html", null ],
    [ "Span::ComponentMetadata", "structSpan_1_1ComponentMetadata.html", null ],
    [ "Span::ComponentRegistry", "classSpan_1_1ComponentRegistry.html", null ],
    [ "Span::ComponentType&lt; T &gt;", "classSpan_1_1ComponentType.html", null ],
    [ "Span::ComponentTypeCounter", "classSpan_1_1ComponentTypeCounter.html", null ],
    [ "Span::ComputeBuffer", "classSpan_1_1ComputeBuffer.html", null ],
    [ "Span::ConstantBuffer&lt; T &gt;", "classSpan_1_1ConstantBuffer.html", null ],
    [ "Span::DepthNormalPass::DepthNormalData", "structSpan_1_1DepthNormalPass_1_1DepthNormalData.html", null ],
    [ "Span::DepthNormalPass", "classSpan_1_1DepthNormalPass.html", null ],
    [ "Span::DirectionalLight", "structSpan_1_1DirectionalLight.html", null ],
    [ "Span::DirectoryWatcher", "classSpan_1_1DirectoryWatcher.html", null ],
    [ "Span::EditorCamera", "structSpan_1_1EditorCamera.html", null ],
    [ "Span::EditorCameraState", "structSpan_1_1EditorCameraState.html", null ],
    [ "Span::EditorFileSystem", "classSpan_1_1EditorFileSystem.html", null ],
    [ "Span::EditorPanel", "classSpan_1_1EditorPanel.html", [
      [ "Span::EnvironmentPanel", "classSpan_1_1EnvironmentPanel.html", null ],
      [ "Span::HierarchyPanel", "classSpan_1_1HierarchyPanel.html", null ],
      [ "Span::InspectorPanel", "classSpan_1_1InspectorPanel.html", null ],
      [ "Span::ProjectBrowserPanel", "classSpan_1_1ProjectBrowserPanel.html", null ],
      [ "Span::SceneViewPanel", "classSpan_1_1SceneViewPanel.html", null ]
    ] ],
    [ "Span::Entity", "structSpan_1_1Entity.html", null ],
    [ "Span::EntityBuilder", "classSpan_1_1EntityBuilder.html", null ],
    [ "Span::EntityID", "structSpan_1_1EntityID.html", null ],
    [ "Span::EntityLocation", "structSpan_1_1EntityLocation.html", null ],
    [ "Span::EntityManager", "classSpan_1_1EntityManager.html", null ],
    [ "Span::EnvironmentSettings", "structSpan_1_1EnvironmentSettings.html", null ],
    [ "std::false_type", null, [
      [ "Span::is_fixed_string< FixedString< N > >", "structSpan_1_1is__fixed__string_3_01FixedString_3_01N_01_4_01_4.html", null ],
      [ "Span::is_fixed_string< T >", "structSpan_1_1is__fixed__string.html", null ]
    ] ],
    [ "Span::FileDialog", "classSpan_1_1FileDialog.html", null ],
    [ "Span::FixedString&lt; N &gt;", "structSpan_1_1FixedString.html", null ],
    [ "Span::GlobalLightData", "structSpan_1_1GlobalLightData.html", null ],
    [ "Span::GraphicsContext", "classSpan_1_1GraphicsContext.html", null ],
    [ "Span::GridPass", "classSpan_1_1GridPass.html", null ],
    [ "Span::GuiManager", "classSpan_1_1GuiManager.html", null ],
    [ "std::hash&lt; Span::EntityID &gt;", "structstd_1_1hash_3_01Span_1_1EntityID_01_4.html", null ],
    [ "Span::IBLBuilder", "classSpan_1_1IBLBuilder.html", null ],
    [ "Span::ICommand", "classSpan_1_1ICommand.html", [
      [ "Span::CreateDirectoryCommand", "classSpan_1_1CreateDirectoryCommand.html", null ],
      [ "Span::CreateFileCommand", "classSpan_1_1CreateFileCommand.html", null ],
      [ "Span::DeleteFileCommand", "classSpan_1_1DeleteFileCommand.html", null ],
      [ "Span::MoveFileCommand", "classSpan_1_1MoveFileCommand.html", null ],
      [ "Span::RenameFileCommand", "classSpan_1_1RenameFileCommand.html", null ]
    ] ],
    [ "Span::IDComponent", "structSpan_1_1IDComponent.html", null ],
    [ "Span::ImGuiUI", "classSpan_1_1ImGuiUI.html", null ],
    [ "Span::Internal::ImGuiVisitor", "structSpan_1_1Internal_1_1ImGuiVisitor.html", null ],
    [ "Span::Input", "classSpan_1_1Input.html", null ],
    [ "Span::Internal::JsonDeserializeVisitor", "structSpan_1_1Internal_1_1JsonDeserializeVisitor.html", null ],
    [ "Span::Internal::JsonSerializeVisitor", "structSpan_1_1Internal_1_1JsonSerializeVisitor.html", null ],
    [ "Span::Layer", "structSpan_1_1Layer.html", null ],
    [ "Span::LayerManager", "classSpan_1_1LayerManager.html", null ],
    [ "Span::LightDataGPU", "structSpan_1_1LightDataGPU.html", null ],
    [ "Span::LightManager", "classSpan_1_1LightManager.html", null ],
    [ "Span::LocalToWorld", "structSpan_1_1LocalToWorld.html", null ],
    [ "Span::Logger", "classSpan_1_1Logger.html", null ],
    [ "Span::Material", "classSpan_1_1Material.html", null ],
    [ "Span::MaterialData", "structSpan_1_1MaterialData.html", null ],
    [ "Span::MaterialPreviewer", "classSpan_1_1MaterialPreviewer.html", null ],
    [ "Span::Matrix4x4", "structSpan_1_1Matrix4x4.html", null ],
    [ "Span::MemoryArena", "classSpan_1_1MemoryArena.html", null ],
    [ "Span::Mesh", "classSpan_1_1Mesh.html", null ],
    [ "Span::MeshFilter", "structSpan_1_1MeshFilter.html", null ],
    [ "Span::MeshRenderer", "structSpan_1_1MeshRenderer.html", null ],
    [ "Span::ModelLoader", "classSpan_1_1ModelLoader.html", null ],
    [ "Span::Name", "structSpan_1_1Name.html", null ],
    [ "Span::PointLight", "structSpan_1_1PointLight.html", null ],
    [ "Span::Quaternion", "structSpan_1_1Quaternion.html", null ],
    [ "Span::Relationship", "structSpan_1_1Relationship.html", null ],
    [ "Span::Renderer", "classSpan_1_1Renderer.html", null ],
    [ "Span::RenderItem", "structSpan_1_1RenderItem.html", null ],
    [ "Span::RenderPassManager", "classSpan_1_1RenderPassManager.html", null ],
    [ "Span::RenderTarget", "classSpan_1_1RenderTarget.html", null ],
    [ "Span::Scene", "classSpan_1_1Scene.html", null ],
    [ "Span::SceneSerializer", "classSpan_1_1SceneSerializer.html", null ],
    [ "Span::SelectionManager", "classSpan_1_1SelectionManager.html", null ],
    [ "Span::Shader", "classSpan_1_1Shader.html", null ],
    [ "Span::ShadowMap", "classSpan_1_1ShadowMap.html", null ],
    [ "Span::ShadowPass", "classSpan_1_1ShadowPass.html", null ],
    [ "Span::SkyboxPass", "classSpan_1_1SkyboxPass.html", null ],
    [ "Span::SpotLight", "structSpan_1_1SpotLight.html", null ],
    [ "Span::SSAOBlurPass", "classSpan_1_1SSAOBlurPass.html", null ],
    [ "Span::SSAOPass::SSAOData", "structSpan_1_1SSAOPass_1_1SSAOData.html", null ],
    [ "Span::SSAOPass", "classSpan_1_1SSAOPass.html", null ],
    [ "Span::System", "classSpan_1_1System.html", [
      [ "Span::CameraSystem", "classSpan_1_1CameraSystem.html", null ],
      [ "Span::EditorCameraSystem", "classSpan_1_1EditorCameraSystem.html", null ],
      [ "Span::RelationshipSystem", "classSpan_1_1RelationshipSystem.html", null ],
      [ "Span::RenderingSystem", "classSpan_1_1RenderingSystem.html", null ],
      [ "Span::TransformSystem", "classSpan_1_1TransformSystem.html", null ]
    ] ],
    [ "Span::Tag", "structSpan_1_1Tag.html", null ],
    [ "Span::TagManager", "classSpan_1_1TagManager.html", null ],
    [ "Span::Texture", "classSpan_1_1Texture.html", null ],
    [ "Span::Time", "classSpan_1_1Time.html", null ],
    [ "Span::Transform", "structSpan_1_1Transform.html", null ],
    [ "Span::TransformData", "structSpan_1_1TransformData.html", null ],
    [ "std::true_type", null, [
      [ "Span::is_fixed_string< FixedString< N > >", "structSpan_1_1is__fixed__string_3_01FixedString_3_01N_01_4_01_4.html", null ]
    ] ],
    [ "Span::Vector2", "structSpan_1_1Vector2.html", null ],
    [ "Span::Vector3", "structSpan_1_1Vector3.html", null ],
    [ "Span::Vector4", "structSpan_1_1Vector4.html", null ],
    [ "Span::Vertex", "structSpan_1_1Vertex.html", null ],
    [ "Span::Window", "classSpan_1_1Window.html", null ],
    [ "Span::WindowDesc", "structSpan_1_1WindowDesc.html", null ],
    [ "Span::World", "classSpan_1_1World.html", null ]
];